import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import dynamic from "next/dynamic";
import Theme from "../providers/ThemeProvider";
import ReduxProvider from "../providers/ReduxProvider";
import Navbar from "@/components/Navbar";
import QueryProvider from "@/providers/QueryProvider";

const AntdProvider = dynamic(() => import("../providers/AntdProvider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NVP Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AntdRegistry>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ReduxProvider>
            <Theme>
              <AntdProvider>
                <Navbar />

                <QueryProvider>
                  <main className="flex flex-row pt-2">
                    <div className="container mx-auto">{children}</div>
                  </main>
                </QueryProvider>
              </AntdProvider>
            </Theme>
          </ReduxProvider>
        </body>
      </html>
    </AntdRegistry>
  );
}
